spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/makini_university_db
    username: postgres
    password: cellulant123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db.migration

server:
  port: 8001

springdoc:
  swagger-ui:
    path: /swagger-ui.html
